### ISSUE TITLE
Exception Handling for missing HTTP Response Status Code (KeyError: 'status'; AttributeError: object has no attribute 'status')

### ISSUE THREAD

**Issue by sodonnell** [sodonnell/rssbot2#1]
**Issue Description:** 

When attempting to fetch an RSS Feed via TravisCI (which blocks all outbound HTTP Requests and returns no HTTP Response), the following expected exception occurs. However, this causes travis-ci to mark the build as failed, which is technically misleading.

This issue is not limited to just HTTP Requests that return no HTTP Response. It also applies to HTTP Responses that the feedparser python module is unable to properly parse, due to a null data response or a non-compatible/un-parsable data format/structure.

**Example Output from a TravisCI workflow:**

```
python3 add_feed.py -u https://hackaday.com/blog/feed/ -a

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/feedparser.py", line 398, in __getattr__
    return self.__getitem__(key)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/feedparser.py", line 356, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'status'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "add_feed.py", line 42, in <module>
    feed_id = rssbot.add_feed(url, active)
  File "/home/travis/build/sodonnell/rssbot2/rssbot2.py", line 87, in add_feed
    rss.status
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/feedparser.py", line 400, in __getattr__
    raise AttributeError("object has no attribute '%s'" % key)
AttributeError: object has no attribute 'status'
```

This is actually not a bug, but expected behavior for such test cases.

**Comment by sodonnell** [comment]
This is technically expected exception handling behavior. 

Travis-ci blocks outbound HTTP Requests, so we are able to validate the test case where these exceptions *should* be thrown.

The Github Actions CI features do not block outbound HTTP requests, so these exceptions do not occur for valid HTTP request URLs. The github actions workflow allows us to then test the actual use case functionality to verify that HTTP responses are valid and able to be parsed as expected.

Both of these are valid test cases.
